name:                hageman
version:             0.1.0.0
github:              "suhrawardi/hageman"
license:             BSD3
author:              "Jarra"
maintainer:          "suhrawardi@gmail.com"
copyright:           "2019 Jarra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hageman#readme>

dependencies:
- alsa-seq
- base >= 4.7 && < 5
- Euterpea > 2.0.0 && < 2.1.0
- HSoM
- random
- UISF

library:
  source-dirs: src

executables:
  hageman-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hageman

tests:
  hageman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hageman
